### PR TITLE
Fixed driver from parsing object files multiple times

### PR DESCRIPTION
**Pull request by marler8997**
The new ObjectFiles class keeps track of which object files were already parsed and prevents driver.d from parsing the same object file twice.

### CODE REVIEW

**Comment by yebblies** [comment]
I'm not sure what you mean by "parsing multiple times".  Can you give me an example and say where the redundant work is done?

**Comment by marler8997** [comment]
It was parsing the same object files multiple times...put in a writef in driver.d where you parse an object file.

**Comment by yebblies** [comment]
Ok I see what you're doing.  Unfortunately I think this is invalid.

While object and library files do not technically need to be parsed multiple times, their symbols _do_ need to be loaded multiple times.

eg these load orders are equivalent:
`a.obj x.lib x.lib y.lib`
`a.obj x.lib y.lib`

But these aren't.
`a.obj x.lib y.lib x.lib`
`a.obj x.lib y.lib`

If the first pass over x generates an undefined symbol that is found in y, and that in turn brings in an undefined symbol that is defined in x, x must be loaded twice for everything to be resolved correctly.

Removing adjacent loads of the same library/object file should be ok.

It appears optlink does this by name:
`link testd.obj+testd.obj` succeeds
`link testd.obj+..\ylink\testd.obj` fails with multiple definition errors.

There is also a behavior difference between olink and optlink here.  With these files:
a.obj

``` d
extern(C) void funx();
void main()
{
    funx();
}
```

x.lib

``` d
extern(C) void funy();
extern(C) void funx()
{
    funy();
}
extern(C) void funxa()
{
}
```

y.lib

``` d
extern(C) void funxa();
extern(C) void funy()
{
    funxa();
}
```

Compiling with optlink or olink works like this:
`link a.obj,,,x.lib+y.lib+x.lib`
Compiling like this only works with optlink:
`link a.obj,,,x.lib+y.lib`

It seems that optlink is re-scanning x.lib for undefined symbols that were in y.lib.  I'm guessing this is because it builds its own hash table internally with all the loadable lib symbols in it.  This is IIRC different from what ld does.

**Comment by marler8997** [comment]
Ah ok I had a feeling that that's why you were scanning the file multiple times.  I'm assuming that you're not ok with parsing the file multiple times as this would be much slower than if you parsed the file once and then resolved unresolved symbols as you loaded the dependent object files.  In that case we'll have to use a different approach to solve this.  I do think however that the ObjectFiles class is a better way to keep track of the files so we can put all the logic to check the object files in one place.   I'll update this PR accordingly and for now make sure to only remove adjacent object files.  (In the example i was linking "SNN.lib" was being parsed like 8 times in a row).

**Comment by yebblies** [comment]
I've done zero work on performance so far.

Last time I was working on this, I wanted to:
1. Separate the file loading and symbol loading.  This would mean having an intermediate format that could represent both omf and coff.  Re-scanning a library would then be trivial.
2. Create a serializer and deserializer for the intermediate format, probably using json.
3. Start creating a test suite using this file format.

This was blocked by mscoff32, so I did that first.

Anyway, it should be fine to keep an ordered list of all libraries and jump back to the beginning of the list once the current library has stopped resolving undefineds, or possibly start at the beginning for each undefined.  I'm not sure how optlink and the ms linker do it, but it should be easy enough to test.

I don't mind replacing WorkQueue with ObjectFiles, although if ObjectFiles contains more than ObjectFiles it needs a better name.  If WorkQueue is no longer used it should be deleted.

**Comment by Orvid** [comment]
It would certainly be nice if we could simply grab the test suite from binutils for example. The vast majority of the tests would have to be disabled at first, but it would certainly be a nice test.

**Pull request closed without merging**
