### PR TITLE
Use dub as a build system

### PR DESCRIPTION
**Pull request by Geod24**
This moves the files to a "source" subfolder, allowing for a latter, less flat package.

It also switch to dub as a build system for the executables, but not the various tests.

Which "link" command is expected at line 52 ? I thought it was optlink, but it didn't compile on my machine.

Please let me know if there is anything you dislike about this.

### CODE REVIEW

**Comment by yebblies** [comment]
I don't mind having dub support, but I want the source layout and makefile to stay as they are for now.

"link" on line 52 is optlink, I suspect it's picking up your visual studio linker.

**Comment by Geod24** [comment]
I just thought it would be easyier to do split it in a more scalable way right now, where only 2 people (Andrej & me) forked your project, than later if you have more people working on it. But if you prefer it flat, I'll update it.

You were right, my shell was picking GNU linker instead of optlink. Fixed that.

However, I'm getting exceptions:

```
bin/olink.exe /MAP testd.obj,teste.exe/CO/NOI
object.Exception@source\symboltable.d(166): Error: 73 unresolved symbols found
----------------object.Exception@source\symboltable.d(166): Error: 73 unresolved symbols found
----------------
0x0044B7EB in pure @safe void std.exception.bailOut(immutable(char)[], uint, const(char[]))
0x00444CA1 in void symboltable.SymbolTable.checkUnresolved() at C:\Cygwin\home\Geod\ylink\source\symboltable.d(167)
```

Will look into it.

**Comment by yebblies** [comment]
I'm planning to do quite a bit of restructuring once the major file formats are supported, so cleaning things up now is not really worthwhile.

Is that the complete error you were getting or did you omit the list of symbols?  If you have the symbol names I can probably tell you what's wrong.

**Comment by Geod24** [comment]
The issues were due to my shell setup, where make default to make -j. This is fine when you build tons of widely reviewed OSS, but has a tendency to break some uncareful makefiles. After few tweak in the Makefile, everything compiles fine. (That's also why I tend to always prefer a tool like dub: you are sure it is working in the same way on all system, thus it's easyier to contribute).

Anyway I changed this to a dub-only commit. Nothing controversial anymore.

**Comment by yebblies** [comment]
I agree, but this is still really a first draft and I don't like to impose too much structure before I'm sure where it's going.

**Pull request merged**
