### PR TITLE
Updated check to only parse objects files once and other updates

### PR DESCRIPTION
**Pull request by marler8997**
I spent a couple hours on this.  I wanted to see how accepting people are of updates to this tool. If this PR gets accepted I'll likely help more.
1. Updated driver.d to only parse object files once
2. Modified ylink command line to use getopt
3. Added usage
4. Added ability to change verbosity
5. Can now use additional include paths on the command line using the -L option

### CODE REVIEW

**Comment by yebblies** [comment]
Contributions are always appreciated, this isn't at the top of my project list these days.
- The dub.json changes look fine.
- The workqueue changes look like a good idea at first glance.
- The getopt changes also look like a good idea/acceptable
- __gshared is not good.  Might as well be tls for now.
- There is already a module with global stuff in it
- Verbosity seems ok
- Wow I didn't put linker paths in already?

I will have a look at this is greater detail tomorrow if I get time, and it would be very helpful if you could:
1. Do one logical change per pull request.
2. Match the existing style - brace on its own line, 4 space indentation
3. Find a reference or example for any behavior changes ("LIBS" jumps out at me)
4. Test your changes by at least compiling all the tools (I think you broke mlink) and at best by running the simple test programs.  olink can also be tested against the dmd test suite, it passes most of the programs that don't use 'export'.

Does that sound reasonable?

**Comment by marler8997** [comment]
Yes that all sounds reasonable:)
1. Did you see my comment about why I used __gshared?  __gshared is slightly faster than regular thread local globals and since this is a single threaded application I thought I would just use it.  I can take it out if it bugs you too much but __gshared is nice because if you ever make it multithreaded it makes it much easier to find all your globals by searching for __gshared so you can fix them case by case.
2. Which module has global stuff in it?  I'll move the verbosity variable to it.
3. So one logical change per request?  I will try but I code pretty fast.  Like I said this commit took me a couple hours and it would take forever to break them up into individual commits, or commit them one by one waiting for PRs to get integrated.  But don't let make you think I sacrifice code quality.   I take pride in my code and put the quality of my code at the highest priority.  It comes from being a perfectionist.
4. I was using Emacs to edit the code and I'm guessing you were using Visual Studio.  I tried to match the VS style but I probably missed some corrections.  Maybe I'll use a tool to fix the whitespace before I commit.
5. I used the LIBS environment variable because I believe thats what gcc uses.  I  figured there's not real harm in using both.
6. I did compile all the subconfigurations I saw in dub.json.
   dub build --config=<subconfig>
   How do I build mlink and run olink on the dmd test suite?

I look forward to working on this.  Again I am a very fast coder so I appreciate good response time so I'm not blocked waiting for approvals. I am excited to see a linker written in D.

**Comment by marler8997** [comment]
P.S. I'm going out of town so my next commit may or may not be in the next couple days.  However usually I would make the changes immediately and push them.

**Comment by yebblies** [comment]
> Did you see my comment about why I used __gshared? __gshared is slightly faster than regular thread local globals and since this is a single threaded application I thought I would just use it. I can take it out if it bugs you too much but __gshared is nice because if you ever make it multithreaded it makes it much easier to find all your globals by searching for __gshared so you can fix them case by case.

I did.  Technically __gshared is faster, but here it won't be measurable.  I have no intention of using mutable globals for multi-threaded configuration, I usually prefer a heap-allocated structure so access can be explicitly passed around.  Anyway, if the globals are all in one module it will be trivial to find them.

> So one logical change per request? I will try but I code pretty fast. Like I said this commit took me a couple hours and it would take forever to break them up into individual commits, or commit them one by one waiting for PRs to get integrated.

I think you misunderstand me.  For example, the change adding `mlink.d` to the dub configuration files has very little to do with the rest of it.  It should have been in its own pull request, and I could have merged it right away.  git rebase would make it trivial to split that change into its own commit.  Some of the other changes are slightly more difficult to split, but at worst it would be a couple of minutes of copy-paste.  If you are not familiar with using git for this, I'm happy to provide specific commands.

I would suggest splitting it into workqueue changes / verbosity changes / getopt / new linker paths / etc

> But don't let make you think I sacrifice code quality. I take pride in my code and put the quality of my code at the highest priority. It comes from being a perfectionist.

It's not that I'm worried about the quality of your code, it's that I have to inspect/test each change individually, and if they are all lumped together it will be more difficult and therefore take longer.

> I was using Emacs to edit the code and I'm guessing you were using Visual Studio. I tried to match the VS style but I probably missed some corrections. Maybe I'll use a tool to fix the whitespace before I commit.

I use notepad++, configured to this style.  FWIW it's pretty much dmd's style.  I expect there is a way to configure emacs to do it this way automatically.  It's also fairly easy to see in github's diff view.

> I used the LIBS environment variable because I believe thats what gcc uses. I figured there's not real harm in using both.

Well, olink is meant to be interface-compatible with optlink, and mlink with microsoft's linker.  If they don't read that variable then neither should we, especially by default.  The interface for ylink open for us to define however we like, within reason.  If/when we were linking elf it would make sense to match what ld/gcc does.

>  did compile all the subconfigurations I saw in dub.json.
> dub build --config=
> How do I build mlink and run olink on the dmd test suite?

I use the makefile.  It's probably not hard to add a dub configuration to build mlink.  (I didn't write the dub config) The tests are pretty much just building a couple of C and D test programs and checking they link correctly with all the linkers.

Have you already got it set up to run dmd's test suit the normal way (with optlink)?  If so, changing sc.ini's LINK command to point to olink.exe instead of optlink will do it.

**Comment by yebblies** [comment]
> I look forward to working on this. Again I am a very fast coder so I appreciate good response time so I'm not blocked waiting for approvals. I am excited to see a linker written in D.

It's good to see others interested in this.  There is a lot of potential here.

**Comment by marler8997** [comment]
Ya I noticed that after I pushed.  Should I push a commit just fixing that issue or should I wait for more feedback?

**Comment by yebblies** [comment]
> Ya I noticed that after I pushed. Should I push a commit just fixing that issue or should I wait for more feedback?

`--amend`?  And there's no real reason I can see for it to be ubyte over int.

Just checking, but you know I'm waiting for you to split this up so I can merge the parts that I'm happy with, right? (eg the makefile change)

**Comment by marler8997** [comment]
oh ok.  You said you knew of some commands to help split up commits? Also, when you say split up the changes do you mean for me to create a branch for each change and make a separate PR for each one?

**Comment by yebblies** [comment]
Yes, creating a new branch is usually the easiest way.

The easiest way is obviously to make multiple small commits as you go, because you can always reorder and combine them later with `git rebase -i`.  It doesn't always work out that way so...

For splitting up commits that can be done by file, I use `git gui`, which sucks, but works well for this.  eg the dub.json changes only touch one file, so it can be done easily.
1. Open git gui
2. Change the radio button to "Amend Last Commit"
3. Unstage the change you want to split out (eg dub.json)
4. Commit
5. Re-stage the change and make a new commit

Now you have two commits instead of one, and can easily make a branch with just the top commit using:

`git checkout -b <newbranch> master`
`git cherry-pick oldbranch`

If the commit you want to split up is not at the top of your branch, you can still use the same procedure using `git rebase -i` and marking the target commit  with 'edit'.

If you google for "how to split up git commits" you'll find plenty of other ways to do the same thing.  If you get stuck let me know.  Many of these changes are even trivial to do by re-branching from master and copy-pasting.

**Comment by marler8997** [comment]
So I'm trying to split up these commits and it's not pretty.  I can easily pull apart the dub changes but splitting apart the code changes is scary.  For example, to split up "getopt" and "verbosity" I would need to remove the verbosity option from getopt and the usage function.  That's fine but then how am I suppose to add those options in the verbosity commit if the getopt change doesn't exist yet?

Just to clarify, you are asking me to make each of the changes based of the parent commit correct? They can't be just separate commits based off each other?

parent -> getopt
parent -> verbosity
parent -> WorkQueue

VS

parent -> getopt -> verbosity -> WorkQueue

I'm assuming you were asking for the first case so you could pick and choose which features you would like to add in.  The problem is these changes can't be split up in that way because they are all interdependent.

**Comment by yebblies** [comment]
> For example, to split up "getopt" and "verbosity" I would need to remove the verbosity option from getopt and the usage function. That's fine but then how am I suppose to add those options in the verbosity commit if the getopt change doesn't exist yet?

Yes, in this case there's no way to make the changes independent.  If you make a pull request for the getopt changes, one for just the verbosity changes can be made after it's merged.  These dependencies get less common as the infrastructure gets more stable.

> Just to clarify, you are asking me to make each of the changes based of the parent commit correct? They can't be just separate commits based off each other?

I don't mind how you organize them on your end, but the pull requests should only contain one logical change.  If the commits are not each based on master then you'll have to wait until the first pull request is merged before making the second, or else the second pull request will also contain the changes from the first one.

Eg if you have changes:
a, b, c, d (depends on c)
Then you can rebase a, b, c onto master and make independent pull requests for them.  If there's something holding up a -  b and c can still be merged.
If they were not rebased on master, then PR a would contain a, PR b would contain a and b, etc

If having them blocked by each other is not a problem (or unavoidable like with getopt/verbosity) then not rebasing them on master is not a problem.

**Comment by marler8997** [comment]
This situation is getting a little concerning for me.  I foresee future development to look like me spending 20 minutes developing useful code, then spending the next day or so waiting for the PR to get accepted.  I would need to keep a list of things I need to do next but can't implement yet because I need to wait for the previous PR to get accepted.

When I work on a project I put all my effort and focus into it.  It takes a while for me to context switch so every time I do it's a big time waster for me.  The PR model you are proposing where I either split up logical changes, or wait for approval on interdependent changes is going to make me have to do alot of context switching and waiting.  I understand why this model is beneficial for you because then you can easily look at each small change and decide what you like.  However I'm not looking to make small changes, I'm looking to make big changes and get this thing finished, stable, and performing as fast as possible.

If I wasn't waiting for this PR to get accepted I would have already spent another 6 or so hours on it accomplishing this.  But then of course you would have had to spend quite a bit of time reviewing those changes.  Maybe I'm just the kind of programmer that doesn't thrive on contributing to other people's projects?  Contributing to others projects is kinda new for me so this is a learning experience.

What do you think about me just working on the fork for a while?  We can keep in contact and then maybe later we could talk about merging again?  Or if you don't like where my fork went we could just develop different linkers.  But I would understand if you weren't comfortable with me using your code as well, you put a lot of time into it I'm sure.

**Comment by yebblies** [comment]
I understand, and I'm the same way - but I think you're overestimating the cost this has to you.  Splitting up the changes usually takes a tiny fraction of the time it took to code them.  In contrast, if your work comes to me as a huge diff with many unrelated changes, I have to work out what you've done and how each thing is connected, which takes much longer because I'm not the one who wrote the code.  This makes reviewing take longer and ends up wasting both our time.

It certainly is a chore the first few times, but it very quickly becomes straightforward.  I use this process for dmd, where I mostly make pull requests, and for work, where I mostly review.  It works very well, with all sorts of changes and projects.

I can't merge this pull request in its current state, even I was 100% on each change (I think you've fixed most of my problems with it actually) because it still has minor formatting problems.  If this was split into 6 pull requests I could most probably merge 5 of them right now.

I am highly confident if you give this method a go you will see how well it works.  I'm also confident I can keep up with the rate of pull requests if they are presented like that.

Worst case, you are of course free to just do the work in your own fork.  Merging later would be the same thing we're discussing now, but it's much harder on a larger scale, especially with architectural changes that I assume are imminent.  With no merge, I can manually extract changes from your fork (assuming you keep it boost) but at that point it's probably less time consuming to just implement it from scratch.  So definitely not ideal, but two diverging forks is still better than only one fork or only one public fork.

Anyway, it's after 4am here so I'm going to go sleep.  My fingers are crossed in the morning I'll have a bunch of small pull requests to merge =D

**Comment by marler8997** [comment]
Ok well we'll see how it goes.  I am out of town right now so you won't be seeing a bunch of pull requests yet :)  So for this commit though, since I can't really split up the changes, what do I need to do to get it merged?

**Comment by yebblies** [comment]
At least split out the single-file changes (makefile, readme, dub.json) and if at all possible the workqueue changes.  I think without the workqueue stuff (and the remaining formatting problems) it's mostly ok now.  I'll have another look tomorrow if I have time.

**Pull request closed without merging**
